[project]
name = "fuck-the-exam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "google>=3.0.0",
    "google-genai>=1.59.0",
    "sqlalchemy>=2.0.45",
    "uvicorn[standard]>=0.40.0",
]
